apiVersion: batch/v1
kind: Job
metadata:
  name: behat
spec:
  template:
    metadata:
      name: behat
    spec:
      containers:
        - name: akeneo
          image: perl
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        - name: selenium
      restartPolicy: Never
